FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

EXTRA_OEMESON += "\
    -DBMCWEB_ENABLE_REDFISH=true \
    -DBMCWEB_ENABLE_DBUS_REST=true \
    -DBMCWEB_ENABLE_STATIC_HOSTING=true \
    -DBMCWEB_ENABLE_SWAGGER_UI=true \
    -DBMCWEB_ENABLE_SSL=true \
    -DBMCWEB_INSECURE_DISABLE_AUTHENTICATION=false \
"

